version: '3.0'
services:
  postgres:
    image: postgres
    restart: always
    container_name: postgres-docker
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: vkhack
      POSTGRES_USER: vkhack
      POSTGRES_PASSWORD: vkhack
    volumes:
      - ./data:/var/lib/postgresql/data
volumes:
  postgres: